### ISSUE TITLE
Does this view DICOM images in 2D?

### ISSUE THREAD

**Issue by yusufalibrahim1994** [tobias2912/VR-DICOM-viewer#1]
I tried to install the apk via sidequest, but after installing it in my Quest 2 it takes a long time to load and never loads so I couldn't understand the details of this project. Does this display DICOM images in VR in a 2D Canvas or does it reconstruct the DICOM images into a 3D model?

Thanks

**Comment by tobias2912** [comment]
The program is very fragile, and missing files will quickly make the program crash. The application does not create any models, it requires both dicom images and a existing 3d model to work. Make sure the images are imported into the correct folder and no components have missing references
